dist: xenial
language: bash
notifications:
  email: false
  slack:
    secure: ZbHCZlSL92KugYzTAEUh8uLfyHwGv1PICcDqVa6CWwag8yjo/Tke0qVCajPM6SKxw/mkzPZyctauVqdNCtdiVR4LbWB5JyRP4qH+DKtsxWFC7JwPOB1b7umzXqo9Ba7GCe5U+NqtyxHzxst5srkDtEwjnzXtOjvQjVKdiJmIBJfUspWuMuVY2u5Tgy3Jbuln8GnX6b6N/YYYXHeU3RFTpTiTN7v9Pzo1NhtZFG+lj3oqkFV7cpl6WGqcqri+XeiG2QKu5er6DZbiS37Pf7EwA5FpN8Ew6GjnCXSsf7nvDmX7Yi8lzOmBeEEHrxwFR6iRsqovop7BTQQpvkZg9+dRae7UHTPvfuqtRBOV3p2Xzgg4glMaQFGWG4XZnRCRCnnwnfLTa14P1OVguSsJlrAojzGY+TpqL39MrKamFLoCWn/XuYxMQatlPNtTECF8WUz1ie5v4lTjzowrE0OyRGBSZ/fD3r88G8Ue3tkhF7MEsEykFS4evANrS5a1ro2IeX+06krvtc4sjwmV9JhPP32QD0mV2KbYnU8zI0DqNSkhTmTjLaEv52FRDvh4ermDjh2IO0564hc2ZL/dNRNfdB0I1g3Fd0iTVpYfp2hgNUSPEXI02MObUjONjPxXa4fUyyipghxHa3HT9fpvaVmMXE++favp9sqr5W0cksE7HwDSjNY=
    on_success: always
    on_failure: always
