dist: xenial
sudo: required
language: bash

notifications:
  email: false
  webhooks: 
    - secure: "Kv4xT/TavVVN7f9/AWGUVyL0thBwaxNGdX5bkymyCkQsqv2xeDVGFkrs98yDY3701c041LJ/5WmUSAG5xSFc4XYJSREJ/zOnhkZpV3qM1YDynpVr9td8/ywkJSgmzK3pnQbshyb0ppPdgVO/lgRZIbgxPyTT49RDXLFC9CUqmDuAbvBV6znLio0ja8bkBk1v3UVO5u9APah3Smja+PvBakCMW9x0+MpTPdPms6q2GKYs2hVGhaSxTxxSMxURYhbUgvq5kQeNgEcAp1hACqL4sqA1dCnU7d/LSQi59ntGidJLHgOq6iVy4NiiYojRsRx/jgBWW0r8bH2Roo5HEGXMyqz5z1X/J/c5Ks8v3fxWDM/at/kvynOQOyTYeWJVZwXdT7l4YTEcU6Bc3GPfuaHIheS1EgKZR8PjOkiyE+Zc7Guqxx0iKpq2QQYbpPM3IGurIwgwt3Ps9joQOcmqRiOl4lP4XXgRKjUC1LPhGQ2FeBqQJ1ptVa/YR82iJj+H1KtuZt6WXmrBVXOp07YKr26DTXI6iW6OAo1IHDjUyiLexoee0NNzOfg5TspHTLBXmT9UCXTbNvC28gJ780blfyLMGjnBSFUqBKeZwe9kREuPevy0OEt3F6e4wouaFVD/syTDg7pCeIeSEjpss6Pqrq0223HADJpmcJjX8ZrcZnWryjw="
