---
- name: Install Apache Web Server
  hosts: host1
  become: yes

  vars:
          src_file: ./index.txt
          dst_file: /var/www/html

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Copy file
      copy:
              src: "{{ src_file }}"
              dest: "{{ dst_file }}"
              mode: 0555
      notify: Restart Apache

    - name: Start and Enable
      service:
        name: apache2
        state: started 
        enabled: yes

  handlers:
    - name: Restart Apache
      service:
              name: apache2
              state: restarted

